import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { createServer } from 'http';
import { Server } from 'socket.io';
import { GameState, Role, Player, ClientAction } from './src/types.js';

// Hosts (Render, Railway, Cloud Run, etc.) inject the port via $PORT.
const PORT = Number(process.env.PORT) || 3000;

// --- Room isolation ----------------------------------------------------------
const rooms = new Map<string, GameState>();
const socketRoom = new Map<string, string>();
const lastChatAt = new Map<string, number>(); // socketId -> last chat timestamp (rate limit)

const CHAT_MIN_INTERVAL_MS = 500;
const MIN_PLAYERS_TO_START = 3;
// Chance the Seer's vision is corrupted into the wrong reading (dirty info).
const DIRTY_INFO_CHANCE = 0.2;

function freshNightResult(): GameState['nightResult'] {
  return {
    healedId: null,
    wolfTargetId: null,
    seerSeenId: null,
    seerResult: null,
    witchSavedId: null,
    witchPoisonId: null,
  };
}

function newGameState(): GameState {
  return {
    status: 'LOBBY',
    players: [],
    timerSeconds: 0,
    votes: {},
    nightResult: freshNightResult(),
    witchPotions: { heal: true, poison: true },
    lastHealedId: null,
    deadThisRound: [],
    nightActed: [],
    round: 0,
    winner: null,
    seq: 0,
    settings: { numWolves: 1, numSeers: 1, numDoctors: 1, numWitches: 0, dayLength: 120, firstNightNoDeath: true }
  };
}

// Advance to a new phase, bumping the phase counter so any in-flight bot
// timeouts scheduled for the previous phase will detect the change and abort.
function setPhase(state: GameState, status: GameState['status'], timerSeconds?: number) {
  state.status = status;
  if (timerSeconds !== undefined) state.timerSeconds = timerSeconds;
  state.seq++;
}

// Start a brand-new night: clear per-night data and advance the night counter.
// Witch potions persist across the whole game, so they are NOT reset here.
function resetNight(state: GameState) {
  state.nightResult = freshNightResult();
  state.votes = {};
  state.nightActed = [];
  state.round++;
}

function markActed(state: GameState, id: string) {
  if (!state.nightActed.includes(id)) state.nightActed.push(id);
}

function chatAllowed(socketId: string): boolean {
  const now = Date.now();
  const last = lastChatAt.get(socketId) || 0;
  if (now - last < CHAT_MIN_INTERVAL_MS) return false;
  lastChatAt.set(socketId, now);
  return true;
}

function normalizeRoomCode(code?: string): string {
  const cleaned = (code || '').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 8);
  return cleaned || 'MAIN';
}

function shuffle<T>(input: readonly T[]): T[] {
  const array = [...input]; // never mutate the caller's array
  let currentIndex = array.length, randomIndex;
  while (currentIndex != 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
  }
  return array;
}

// Most voted target. Two passes so the result is order-independent; a tie -> null.
function tally(votes: Record<string, string>): string | null {
  const counts: Record<string, number> = {};
  for (const target of Object.values(votes)) {
    if (target === 'skip') continue;
    counts[target] = (counts[target] || 0) + 1;
  }
  const max = Math.max(0, ...Object.values(counts));
  if (max === 0) return null;
  const top = Object.keys(counts).filter(id => counts[id] === max);
  return top.length === 1 ? top[0] : null;
}

// The Seer's reading, randomly corrupted (item: dirty info, generated by chance).
function computeSeerResult(state: GameState, targetId: string): 'Werewolf' | 'Villager' {
  const target = state.players.find(p => p.id === targetId);
  const truth: 'Werewolf' | 'Villager' = target?.role === 'Werewolf' ? 'Werewolf' : 'Villager';
  if (Math.random() < DIRTY_INFO_CHANCE) {
    return truth === 'Werewolf' ? 'Villager' : 'Werewolf';
  }
  return truth;
}

// --- Per-player state filtering ---------------------------------------------
function viewFor(viewer: Player, state: GameState): GameState {
  const isGhost = !viewer.isAlive;
  const seeAll = viewer.isModerator || isGhost; // host & dead spectators see everything

  const players = state.players.map(p => {
    let canSeeRole = seeAll || p.id === viewer.id;
    if (viewer.role === 'Werewolf' && p.role === 'Werewolf') canSeeRole = true; // wolves know each other
    return canSeeRole ? p : { ...p, role: null };
    // NOTE: the Seer no longer sees the true role of who they inspect — they only
    // get `seerResult`, which may be a lie. This makes dirty info undetectable.
  });

  const seerAllowed = seeAll || viewer.role === 'Seer';
  const wolfAllowed = seeAll || viewer.role === 'Werewolf';
  const witchAllowed = seeAll || viewer.role === 'Witch';
  const docAllowed = seeAll || viewer.role === 'Doctor';

  return {
    ...state,
    players,
    nightResult: {
      seerSeenId: seerAllowed ? state.nightResult.seerSeenId : null,
      seerResult: seerAllowed ? state.nightResult.seerResult : null,
      // The wolves' victim is known to the wolves AND to the Witch (her power).
      wolfTargetId: (wolfAllowed || witchAllowed) ? state.nightResult.wolfTargetId : null,
      healedId: docAllowed ? state.nightResult.healedId : null,
      witchSavedId: witchAllowed ? state.nightResult.witchSavedId : null,
      witchPoisonId: witchAllowed ? state.nightResult.witchPoisonId : null,
    },
    witchPotions: witchAllowed ? state.witchPotions : { heal: false, poison: false },
    lastHealedId: docAllowed ? state.lastHealedId : null,
    nightActed: seeAll ? state.nightActed : [], // only the host needs the acted list
    votes: (state.status === 'NIGHT_WOLVES' && !wolfAllowed) ? {} : state.votes,
  };
}

function broadcast(io: Server, code: string) {
  const state = rooms.get(code);
  if (!state) return;
  for (const p of state.players) {
    io.to(p.socketId).emit('gameState', viewFor(p, state));
  }
}

// Recipients of the private wolf-pack chat: living wolves + the moderator.
function wolfChatRecipients(state: GameState): string[] {
  return state.players
    .filter(p => (p.role === 'Werewolf' && p.isAlive) || p.isModerator)
    .map(p => p.socketId);
}

function checkWinCondition(state: GameState) {
  const alivePlayers = state.players.filter(p => !p.isModerator && p.isAlive);
  const aliveWolves = alivePlayers.filter(p => p.role === 'Werewolf');
  const aliveVillagers = alivePlayers.filter(p => p.role !== 'Werewolf');

  if (aliveWolves.length === 0) {
    state.winner = 'Villagers';
    state.status = 'END';
  } else if (aliveWolves.length >= aliveVillagers.length) {
    state.winner = 'Werewolves';
    state.status = 'END';
  }
}

function killPlayer(state: GameState, id: string) {
  const p = state.players.find(x => x.id === id);
  if (p && p.isAlive) {
    p.isAlive = false;
    if (!state.deadThisRound.includes(id)) state.deadThisRound.push(id);
  }
}

function processNightResults(state: GameState) {
  const { healedId, wolfTargetId, witchSavedId, witchPoisonId } = state.nightResult;
  state.deadThisRound = [];

  // Item: the first night passes with no deaths (a calm opening, Seer still peeks).
  const firstNightSafe = state.settings.firstNightNoDeath && state.round === 1;

  if (!firstNightSafe) {
    const savedByDoctor = !!wolfTargetId && wolfTargetId === healedId;
    const savedByWitch = !!wolfTargetId && wolfTargetId === witchSavedId;
    if (wolfTargetId && !savedByDoctor && !savedByWitch) killPlayer(state, wolfTargetId);
    if (witchPoisonId) killPlayer(state, witchPoisonId); // the death potion ignores protection
  }

  state.lastHealedId = healedId; // remember so the Doctor can't repeat next night
  setPhase(state, 'DAY_ANNOUNCE', 6);
  checkWinCondition(state);
}

// After the Doctor's turn, the Witch acts (if an alive Witch still has a potion);
// otherwise resolve the night immediately.
function afterDoctor(state: GameState) {
  const aliveWitch = state.players.find(p => p.role === 'Witch' && p.isAlive);
  const hasPotion = state.witchPotions.heal || state.witchPotions.poison;
  if (aliveWitch && hasPotion) {
    setPhase(state, 'NIGHT_WITCH', 30);
  } else {
    processNightResults(state);
  }
}

function processDayVoting(state: GameState) {
  const killedId = tally(state.votes);

  state.deadThisRound = [];
  if (killedId) killPlayer(state, killedId);

  checkWinCondition(state);
  if (state.status !== 'END') {
    // Show who was executed via DAY_ANNOUNCE, then head into the next night.
    resetNight(state);
    setPhase(state, 'NIGHT_START', 4);
  } else {
    state.seq++; // game ended: invalidate any pending bot timeouts
  }
}

function triggerBots(io: Server, code: string) {
  const state = rooms.get(code);
  if (!state) return;

  const seq = state.seq;

  if (state.status === 'NIGHT_SEER') {
    const seerBots = state.players.filter(p => p.isBot && p.isAlive && p.role === 'Seer');
    if (seerBots.length > 0 && !state.nightResult.seerSeenId) {
       const others = state.players.filter(p => p.id !== seerBots[0].id && p.isAlive && !p.isModerator);
       if (others.length > 0) {
         const targetId = others[Math.floor(Math.random() * others.length)].id;
         state.nightResult.seerSeenId = targetId;
         state.nightResult.seerResult = computeSeerResult(state, targetId);
         markActed(state, seerBots[0].id);
         setTimeout(() => {
           const s = rooms.get(code);
           if (!s || s.seq !== seq || s.status !== 'NIGHT_SEER') return;
           s.votes = {};
           setPhase(s, 'NIGHT_WOLVES', 30);
           broadcast(io, code);
           triggerBots(io, code);
         }, 2500);
       }
    }
  } else if (state.status === 'NIGHT_WOLVES') {
    const wolfBots = state.players.filter(p => p.isBot && p.isAlive && p.role === 'Werewolf');
    wolfBots.forEach(bot => {
      const targets = state.players.filter(p => p.isAlive && p.role !== 'Werewolf' && !p.isModerator);
      if (targets.length > 0) {
        state.votes[bot.id] = targets[Math.floor(Math.random() * targets.length)].id;
        markActed(state, bot.id);
      }
    });

    const humanWolves = state.players.filter(p => !p.isBot && p.isAlive && p.role === 'Werewolf');
    if (humanWolves.length === 0 && wolfBots.length > 0) {
      setTimeout(() => {
        const s = rooms.get(code);
        if (!s || s.seq !== seq || s.status !== 'NIGHT_WOLVES') return;
        s.nightResult.wolfTargetId = tally(s.votes);
        setPhase(s, 'NIGHT_DOCTOR', 30);
        broadcast(io, code);
        triggerBots(io, code);
      }, 3000);
    }
  } else if (state.status === 'NIGHT_DOCTOR') {
     const docBots = state.players.filter(p => p.isBot && p.isAlive && p.role === 'Doctor');
     if (docBots.length > 0 && !state.nightResult.healedId) {
        const others = state.players.filter(p => p.isAlive && !p.isModerator && p.id !== state.lastHealedId);
        if (others.length > 0) {
            state.nightResult.healedId = others[Math.floor(Math.random() * others.length)].id;
            markActed(state, docBots[0].id);
            setTimeout(() => {
                const s = rooms.get(code);
                if (!s || s.seq !== seq || s.status !== 'NIGHT_DOCTOR') return;
                afterDoctor(s);
                broadcast(io, code);
                triggerBots(io, code);
            }, 2500);
        }
     }
  } else if (state.status === 'NIGHT_WITCH') {
     const aliveWitch = state.players.find(p => p.role === 'Witch' && p.isAlive);
     // A bot Witch (or a missing one) simply passes so the night can resolve.
     if (!aliveWitch || aliveWitch.isBot) {
        setTimeout(() => {
          const s = rooms.get(code);
          if (!s || s.seq !== seq || s.status !== 'NIGHT_WITCH') return;
          processNightResults(s);
          broadcast(io, code);
          triggerBots(io, code);
        }, 2000);
     }
  } else if (state.status === 'DAY_DISCUSS') {
       const bots = state.players.filter(p => p.isBot && p.isAlive);
       if (bots.length > 0) {
           setTimeout(() => {
              const s = rooms.get(code);
              if (s && s.status === 'DAY_DISCUSS') {
                 bots.forEach(bot => {
                    if (Math.random() < 0.25) {
                       const emojis = ['👀', '🤔', '🤨', '😅', '😱', '👎'];
                       const em = emojis[Math.random() * emojis.length | 0];
                       io.to(code).emit('emojiReaction', { id: Math.random().toString(), emoji: em, senderId: bot.id, timestamp: Date.now() });
                    }
                 });
                 triggerBots(io, code);
              }
           }, Math.random() * 3000 + 3000);
       }
  } else if (state.status === 'DAY_VOTING') {
      const bots = state.players.filter(p => p.isBot && p.isAlive);
      let botVoted = false;
      bots.forEach(bot => {
         if (!state.votes[bot.id]) {
           const others = state.players.filter(p => p.isAlive && p.id !== bot.id && !p.isModerator);
           if (others.length > 0) {
              state.votes[bot.id] = others[Math.floor(Math.random() * others.length)].id;
              botVoted = true;
           }
         }
      });
      if (botVoted) {
         const aliveNonMods = state.players.filter(x => !x.isModerator && x.isAlive);
         if (Object.keys(state.votes).length >= aliveNonMods.length) {
            setTimeout(() => {
                const s = rooms.get(code);
                if (!s || s.seq !== seq || s.status !== 'DAY_VOTING') return;
                processDayVoting(s);
                broadcast(io, code);
                triggerBots(io, code);
            }, 1500);
         }
      }
  }
}

async function startServer() {
  const app = express();
  const httpServer = createServer(app);
  const io = new Server(httpServer, { cors: { origin: '*' } });

  io.on('connection', (socket) => {
    socket.on('action', (action: ClientAction) => {
      if (action.type === 'JOIN') {
        const code = normalizeRoomCode(action.roomCode);
        let state = rooms.get(code);
        if (!state) {
          state = newGameState();
          rooms.set(code, state);
        }
        const existing = state.players.find(p => p.socketId === socket.id);
        if (!existing) {
          const hasModerator = state.players.some(p => p.isModerator);
          const isModerator = action.isModerator && !hasModerator;
          state.players.push({
            id: socket.id,
            socketId: socket.id,
            name: action.name,
            isModerator,
            isAlive: true,
            role: null
          });
        }
        socketRoom.set(socket.id, code);
        socket.join(code);
        broadcast(io, code);
        return;
      }

      const code = socketRoom.get(socket.id);
      if (!code) return;
      const state = rooms.get(code);
      if (!state) return;

      let changed = false;

      switch(action.type) {
        case 'ADD_BOT': {
          const p = state.players.find(p => p.socketId === socket.id);
          if (p?.isModerator && state.status === 'LOBBY') {
            const botCount = state.players.filter(x => x.isBot).length;
            const botId = 'bot_' + Math.random().toString(36).substring(2, 9);
            state.players.push({
              id: botId,
              name: 'Bot ' + (botCount + 1),
              socketId: botId,
              isModerator: false,
              isAlive: true,
              role: null,
              isBot: true
            });
            changed = true;
          }
          break;
        }
        case 'REMOVE_BOT': {
          const p = state.players.find(p => p.socketId === socket.id);
          if (p?.isModerator && state.status === 'LOBBY') {
            // Remove the most recently added bot.
            for (let i = state.players.length - 1; i >= 0; i--) {
              if (state.players[i].isBot) { state.players.splice(i, 1); changed = true; break; }
            }
          }
          break;
        }
        case 'START_GAME': {
          const p = state.players.find(p => p.socketId === socket.id);
          if (p?.isModerator && state.status === 'LOBBY') {
            const nonMods = state.players.filter(x => !x.isModerator);

            const numWolves = Math.max(1, Math.floor(action.settings.numWolves) || 1);
            const numSeers = Math.max(0, Math.floor(action.settings.numSeers) || 0);
            const numDoctors = Math.max(0, Math.floor(action.settings.numDoctors) || 0);
            const numWitches = Math.max(0, Math.floor(action.settings.numWitches) || 0);
            const dayLength = Math.min(900, Math.max(30, Math.floor(action.settings.dayLength) || 120));
            const firstNightNoDeath = !!action.settings.firstNightNoDeath;
            const specials = numWolves + numSeers + numDoctors + numWitches;

            const tooFewPlayers = nonMods.length < MIN_PLAYERS_TO_START;
            const rolesDontFit = specials >= nonMods.length; // need >=1 villager
            const wolvesAlreadyWin = numWolves * 2 >= nonMods.length;
            if (tooFewPlayers || rolesDontFit || wolvesAlreadyWin) {
              socket.emit('actionError', {
                message: tooFewPlayers
                  ? `Need at least ${MIN_PLAYERS_TO_START} players to start.`
                  : 'Invalid role counts for this number of players.'
              });
              break;
            }

            state.settings = { numWolves, numSeers, numDoctors, numWitches, dayLength, firstNightNoDeath };

            const rolesPool: string[] = [];
            for(let i=0; i<numWolves; i++) rolesPool.push('Werewolf');
            for(let i=0; i<numSeers; i++) rolesPool.push('Seer');
            for(let i=0; i<numDoctors; i++) rolesPool.push('Doctor');
            for(let i=0; i<numWitches; i++) rolesPool.push('Witch');
            while(rolesPool.length < nonMods.length) rolesPool.push('Villager');

            const shuffled = shuffle(rolesPool);
            nonMods.forEach((player, i) => {
              player.role = shuffled[i] as Role;
              player.isAlive = true;
            });

            state.winner = null;
            state.deadThisRound = [];
            state.lastHealedId = null;
            state.witchPotions = { heal: true, poison: true };
            state.round = 0;
            state.nightActed = [];
            setPhase(state, 'ROLE_REVEAL', 12);
            changed = true;
          }
          break;
        }
        case 'NEXT_PHASE': {
          const p = state.players.find(p => p.socketId === socket.id);
          if (p?.isModerator) {
             // Guarantee players get at least the full reveal time to read their
             // role — the host cannot skip ROLE_REVEAL until the timer runs out.
             if (state.status === 'ROLE_REVEAL' && state.timerSeconds > 0) break;

             if (state.status === 'ROLE_REVEAL') {
                resetNight(state);
                setPhase(state, 'NIGHT_START', 4);
             } else if (state.status === 'NIGHT_START') {
                 setPhase(state, 'NIGHT_SEER', 30);
             } else if (state.status === 'NIGHT_SEER') {
                 state.votes = {};
                 setPhase(state, 'NIGHT_WOLVES', 30);
             } else if (state.status === 'NIGHT_WOLVES') {
                 state.nightResult.wolfTargetId = tally(state.votes);
                 setPhase(state, 'NIGHT_DOCTOR', 30);
             } else if (state.status === 'NIGHT_DOCTOR') {
                 afterDoctor(state);
             } else if (state.status === 'NIGHT_WITCH') {
                 processNightResults(state);
             } else if (state.status === 'DAY_ANNOUNCE') {
                 setPhase(state, 'DAY_DISCUSS', state.settings.dayLength);
             } else if (state.status === 'DAY_DISCUSS') {
                 state.votes = {};
                 setPhase(state, 'DAY_VOTING', 30);
             } else if (state.status === 'DAY_VOTING') {
                 processDayVoting(state);
             }
             changed = true;
          }
          break;
        }
        case 'SKIP_TO_VOTE': {
           // Only the host may cut the discussion short and start the vote.
           if (state.status === 'DAY_DISCUSS') {
              const p = state.players.find(p => p.socketId === socket.id);
              if (p?.isModerator) {
                 state.votes = {};
                 setPhase(state, 'DAY_VOTING', 30);
                 changed = true;
              }
           }
           break;
        }
        case 'SEER_SEE': {
           // Only one inspection per night, and it cannot be re-rolled.
           if (state.status === 'NIGHT_SEER' && !state.nightResult.seerSeenId) {
             const seer = state.players.find(p => p.socketId === socket.id);
             if (seer?.role === 'Seer' && seer.isAlive) {
                state.nightResult.seerSeenId = action.targetId;
                state.nightResult.seerResult = computeSeerResult(state, action.targetId);
                markActed(state, seer.id);
                changed = true;
             }
           }
           break;
        }
        case 'SEER_CONFIRM': {
           if (state.status === 'NIGHT_SEER') {
             state.votes = {};
             setPhase(state, 'NIGHT_WOLVES', 30);
             changed = true;
           }
           break;
        }
        case 'WOLF_VOTE': {
           if (state.status === 'NIGHT_WOLVES') {
             const wolf = state.players.find(p => p.socketId === socket.id);
             if (wolf?.role !== 'Werewolf' || !wolf.isAlive) break;
             state.votes[socket.id] = action.targetId;
             markActed(state, wolf.id);
             changed = true;

             const humanWolves = state.players.filter(p => p.role === 'Werewolf' && !p.isModerator && p.isAlive && !p.isBot);
             const allHumanWolvesVoted = humanWolves.every(w => state.votes[w.id]);

             if (allHumanWolvesVoted) {
                state.nightResult.wolfTargetId = tally(state.votes);
                setPhase(state, 'NIGHT_DOCTOR', 30);
             }
           }
           break;
        }
        case 'WOLF_CONFIRM': {
           if (state.status === 'NIGHT_WOLVES') {
              state.nightResult.wolfTargetId = tally(state.votes);
              setPhase(state, 'NIGHT_DOCTOR', 30);
              changed = true;
           }
           break;
        }
        case 'WOLF_CHAT': {
           const p = state.players.find(p => p.socketId === socket.id);
           const isNight = state.status.startsWith('NIGHT');
           if (p?.role === 'Werewolf' && p.isAlive && isNight && chatAllowed(socket.id)) {
              const text = action.text ? action.text.slice(0, 200) : undefined;
              const msg = { id: Math.random().toString(), text, emoji: action.emoji, senderId: socket.id, timestamp: Date.now() };
              wolfChatRecipients(state).forEach(sid => io.to(sid).emit('wolfMessage', msg));
           }
           break;
        }
        case 'DOCTOR_HEAL': {
           if (state.status === 'NIGHT_DOCTOR') {
             const doc = state.players.find(p => p.socketId === socket.id);
             if (doc?.role !== 'Doctor' || !doc.isAlive) break;
             if (action.targetId === state.lastHealedId) {
               socket.emit('actionError', { message: 'You already saved that player last night.' });
               break;
             }
             state.nightResult.healedId = action.targetId;
             markActed(state, doc.id);
             changed = true;
             afterDoctor(state);
           }
           break;
        }
        case 'WITCH_HEAL': {
           if (state.status === 'NIGHT_WITCH') {
             const witch = state.players.find(p => p.socketId === socket.id);
             if (witch?.role !== 'Witch' || !witch.isAlive) break;
             if (state.witchPotions.heal && state.nightResult.wolfTargetId) {
                state.nightResult.witchSavedId = state.nightResult.wolfTargetId;
                state.witchPotions.heal = false;
                changed = true;
             }
           }
           break;
        }
        case 'WITCH_POISON': {
           if (state.status === 'NIGHT_WITCH') {
             const witch = state.players.find(p => p.socketId === socket.id);
             if (witch?.role !== 'Witch' || !witch.isAlive) break;
             const target = state.players.find(p => p.id === action.targetId);
             if (state.witchPotions.poison && target && target.isAlive && !target.isModerator) {
                state.nightResult.witchPoisonId = action.targetId;
                state.witchPotions.poison = false;
                changed = true;
             }
           }
           break;
        }
        case 'WITCH_PASS': {
           if (state.status === 'NIGHT_WITCH') {
             const witch = state.players.find(p => p.socketId === socket.id);
             if (witch?.role === 'Witch' && witch.isAlive) {
                markActed(state, witch.id);
                processNightResults(state);
                changed = true;
             }
           }
           break;
        }
        case 'DAY_VOTE': {
           if (state.status === 'DAY_VOTING') {
              state.votes[socket.id] = action.targetId;
              changed = true;

              const aliveNonMods = state.players.filter(x => !x.isModerator && x.isAlive);
              if (Object.keys(state.votes).length >= aliveNonMods.length) {
                 processDayVoting(state);
              }
           }
           break;
        }
        case 'RESTART': {
           const p = state.players.find(p => p.socketId === socket.id);
           if (p?.isModerator) {
              state.votes = {};
              state.winner = null;
              state.lastHealedId = null;
              state.nightResult = freshNightResult();
              state.witchPotions = { heal: true, poison: true };
              state.round = 0;
              state.nightActed = [];
              state.deadThisRound = [];
              state.players.forEach(player => {
                  player.role = null;
                  player.isAlive = true;
              });
              setPhase(state, 'LOBBY', 0);
              changed = true;
           }
           break;
        }
        case 'EMOJI_REACTION': {
           if (state.status === 'DAY_DISCUSS' && chatAllowed(socket.id)) {
               io.to(code).emit('emojiReaction', { id: Math.random().toString(), emoji: action.emoji, senderId: socket.id, timestamp: Date.now() });
           }
           break;
        }
        case 'GHOST_CHAT': {
           const p = state.players.find(p => p.socketId === socket.id);
           if (p && !p.isAlive && ['DAY_DISCUSS', 'DAY_VOTING'].includes(state.status) && chatAllowed(socket.id)) {
               const text = action.text ? action.text.slice(0, 200) : undefined;
               io.to(code).emit('ghostMessage', { id: Math.random().toString(), text, emoji: action.emoji, senderId: socket.id, timestamp: Date.now() });
           }
           break;
        }
      }

      if (changed) {
        broadcast(io, code);
        triggerBots(io, code);
      }
    });

    socket.on('disconnect', () => {
       socketRoom.delete(socket.id);
       lastChatAt.delete(socket.id);
       // Rooms intentionally stay open so players can reconnect.
    });
  });

  setInterval(() => {
    for (const [code, state] of rooms) {
      if (state.timerSeconds > 0) {
        state.timerSeconds--;
        if (state.timerSeconds <= 0) {
          if (state.status === 'DAY_DISCUSS') {
             state.votes = {};
             setPhase(state, 'DAY_VOTING', 30);
          } else if (state.status === 'ROLE_REVEAL') {
             resetNight(state);
             setPhase(state, 'NIGHT_START', 4);
          } else if (state.status === 'NIGHT_START') {
             setPhase(state, 'NIGHT_SEER', 30);
          } else if (state.status === 'NIGHT_SEER') {
             state.votes = {};
             setPhase(state, 'NIGHT_WOLVES', 30);
          } else if (state.status === 'NIGHT_WOLVES') {
             state.nightResult.wolfTargetId = tally(state.votes);
             setPhase(state, 'NIGHT_DOCTOR', 30);
          } else if (state.status === 'NIGHT_DOCTOR') {
             afterDoctor(state);
          } else if (state.status === 'NIGHT_WITCH') {
             processNightResults(state);
          } else if (state.status === 'DAY_ANNOUNCE') {
             setPhase(state, 'DAY_DISCUSS', state.settings?.dayLength || 120);
          } else if (state.status === 'DAY_VOTING') {
             processDayVoting(state);
          }
          broadcast(io, code);
          triggerBots(io, code);
        } else {
          broadcast(io, code);
        }
      }

      // Auto-skip night roles that have nobody alive to act.
      if (state.status === 'NIGHT_SEER') {
          if (state.players.filter(p => p.role === 'Seer' && p.isAlive).length === 0) {
               state.votes = {};
               setPhase(state, 'NIGHT_WOLVES', 30);
               broadcast(io, code);
               triggerBots(io, code);
          }
      } else if (state.status === 'NIGHT_DOCTOR') {
          if (state.players.filter(p => p.role === 'Doctor' && p.isAlive).length === 0) {
               afterDoctor(state);
               broadcast(io, code);
               triggerBots(io, code);
          }
      } else if (state.status === 'NIGHT_WITCH') {
          if (state.players.filter(p => p.role === 'Witch' && p.isAlive).length === 0) {
               processNightResults(state);
               broadcast(io, code);
               triggerBots(io, code);
          }
      }
    }
  }, 1000);

  app.get('/api/health', (req, res) => res.json({ status: 'ok' }));

  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({ server: { middlewareMode: true }, appType: 'spa' });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(process.cwd(), 'dist')));
    app.get('*', (req, res) => res.sendFile(path.join(process.cwd(), 'dist', 'index.html')));
  }

  httpServer.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
